### ISSUE TITLE
Tried running, failed. Output from command

### ISSUE THREAD

**Issue by GIneck** [obiequack/setup-scripts#1]
[man@man-virtualbox setup-scripts]$ sudo ./setup.sh 
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
warning: git-2.35.1-1 is up to date -- reinstalling
:: There are 24 members in group base-devel:
:: Repository core
   1) autoconf  2) automake  3) binutils  4) bison  5) fakeroot  6) file
   7) findutils  8) flex  9) gawk  10) gcc  11) gettext  12) grep  13) groff
   14) gzip  15) libtool  16) m4  17) make  18) pacman  19) patch  20) pkgconf
   21) sed  22) sudo  23) texinfo  24) which

Enter a selection (default=all): 
warning: binutils-2.36.1-3 is up to date -- reinstalling
warning: fakeroot-1.27-1 is up to date -- reinstalling
warning: file-5.41-1 is up to date -- reinstalling
warning: findutils-4.9.0-1 is up to date -- reinstalling
warning: gawk-5.1.1-1 is up to date -- reinstalling
warning: gcc-11.1.0-3 is up to date -- reinstalling
warning: gettext-0.21-1 is up to date -- reinstalling
warning: grep-3.7-1 is up to date -- reinstalling
warning: groff-1.22.4-6 is up to date -- reinstalling
warning: gzip-1.11-1 is up to date -- reinstalling
warning: libtool-2.4.6+42+gb88cebd5-16 is up to date -- reinstalling
warning: pacman-6.0.1-3 is up to date -- reinstalling
warning: sed-4.8-1 is up to date -- reinstalling
warning: sudo-1.9.9-2 is up to date -- reinstalling
warning: texinfo-6.8-2 is up to date -- reinstalling
warning: which-2.21-5 is up to date -- reinstalling
error: target not found: xfreerdp
warning: steam-manjaro-1.0.0.74-1 is up to date -- reinstalling
error: target not found: cockpit-navigator
./setup.sh: line 2: yay: command not found
Failed to enable unit: Unit file clamav-daemon.service does not exist.
Failed to enable unit: Unit file clamav-freshclam.service does not exist.
sudo: freshclam: command not found
Failed to enable unit: Unit file xrdp.service does not exist.
Failed to enable unit: Unit file cockpit.socket does not exist.

(gio open:1297): GLib-GIO-CRITICAL **: 14:50:02.820: g_dbus_connection_flush: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /home/man/.Xa

**Comment by GIneck** [comment]
This is after a clean install and update of Manjaro. The only difference being the installation of bash.

**Comment by eternalevelyn** [comment]
Hmmmmmm. I'll look into it, report back.

**Comment by eternalevelyn** [comment]
Okay. Pushed two commits that should fix it. Test again?

**Comment by GIneck** [comment]
Spotify failed.

:: There are 4 providers available for spotify:
:: Repository AUR
    1) spotify 2) spotify-dev 3) spotify-legacy 4) spotify094 

Enter a number (default=1): ==> 1
 -> Could not find all required packages:
	libx264.so=164-64 (Wanted by: librewolf-bin -> ffmpeg4.4)
Created symlink /etc/systemd/system/multi-user.target.wants/clamav-daemon.service → /usr/lib/systemd/system/clamav-daemon.service.
Created symlink /etc/systemd/system/sockets.target.wants/clamav-daemon.socket → /usr/lib/systemd/system/clamav-daemon.socket.
Created symlink /etc/systemd/system/multi-user.target.wants/clamav-freshclam.service → /usr/lib/systemd/system/clamav-freshclam.service.
ERROR: /var/log/clamav/freshclam.log is locked by another process
ERROR: Problem with internal logger (UpdateLogFile = /var/log/clamav/freshclam.log).
ERROR: initialize: libfreshclam init failed.
ERROR: Initialization error!
Failed to enable unit: Unit file xrdp.service does not exist.
Created symlink /etc/systemd/system/sockets.target.wants/cockpit.socket → /usr/lib/systemd/system/cockpit.socket.

(gio open:3055): GLib-GIO-CRITICAL **: 17:19:48.775: g_dbus_connection_flush: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /home/man/.Xauthority which is owned by man.)

**Comment by eternalevelyn** [comment]
Pushed a commit that should fix it.

**Comment by GIneck** [comment]
Spotify completed: 

ERROR: /var/log/clamav/freshclam.log is locked by another process
ERROR: Problem with internal logger (UpdateLogFile = /var/log/clamav/freshclam.log).
ERROR: initialize: libfreshclam init failed.
ERROR: Initialization error!
Failed to enable unit: Unit file xrdp.service does not exist

**Comment by eternalevelyn** [comment]
that means that it should work.  those errors don't matter much

**Comment by eternalevelyn** [comment]
did it work?
